name: Push built packages to Cloudsmith
inputs:
  cloudsmithAPIKey:
    description: Secret Cloudsmith API key
    required: true
  cloudsmithNamespace:
    description: Cloudsmith namespace (org name)
    required: false
  artifactDirectory:
    description: Directory containing package artifacts
    required: true
runs:
  using: "composite"
  steps:

  - name:  List build artifacts
    working-directory: ${{ inputs.artifactDirectory }}
    shell: /bin/bash -ex {0}
    run: ls -R

  - name: Upload packages to Cloudsmith
    env:
      CLOUDSMITH_API_KEY: ${{ inputs.cloudsmithAPIKey }}
      CLOUDSMITH_NAMESPACE: ${{ inputs.cloudsmithNamespace }}
      ARTIFACT_DIRECTORY: ${{ inputs.artifactDirectory }}
    shell: /bin/bash -ex {0}
    run: cloudsmithupload  --package-directory $ARTIFACT_DIRECTORY
